### PR TITLE
Create Leftover-recipes-generator.md

### LINKED ISSUE #2848: [AI Agent idea] Leftover Recipes Generator
### Description

A food recipe generator that suggest you some delicious and creative recipes based on the leftovers you have on hand.

### PR DESCRIPTION
**Pull request by khushminder270**
Fixes #2848
## 📝 Description

Add a brief description.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

lol

### CODE REVIEW

**Comment by khushminder270** [comment]
Please add **hacktoberfest-accepted** label

**Comment by khushminder270** [comment]
@AruSeito Please review and merge the changes

**Comment by khushminder270** [comment]
@AruSeito  please review and merge the changes

**Comment by wenzhuo2022** [comment]
Dear @khushminder270 , we found you have called the variable via {xxx}. We only support to call the variable via {{xxx}}. Could you please update your AI Agent and reply to this comment? 
image

**Comment by khushminder270** [comment]
> Dear @khushminder270 , we found you have called the variable via {xxx}. We only support to call the variable via {{xxx}}. Could you please update your AI Agent and reply to this comment? image

>@wenzhuo2022  Done

**Comment by khushminder270** [comment]
@wenzhuo2022  done with the reviewed changes

**Pull request merged**
