### PR TITLE
English to Hindi translator

### PR DESCRIPTION
**Pull request by ayan-joshi**
## 📝 Description

Added a English to Hindi Translator as mentioned in the issue #2833 

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ayan-joshi** [comment]
@AruSeito have a look sir

**Comment by wenzhuo2022** [comment]
Dear @ayan-joshi , sorry for the late reply. Could you please change the link to illa.ai xxx so that we can review it? You can find the link here:
image

image

**Comment by ayan-joshi** [comment]
> @wenzhuo2022 yes sorry I closed it by mistake you can view it now , I think it's fine to be merge @AruSeito

@AruSeito @wenzhuo2022

**Comment by ayan-joshi** [comment]
Can u please merge the pr @AruSeito @wenzhuo2022 @donqu1xotechina

**Comment by donqu1xotechina** [comment]
@ayan-joshi 
Hey mate:
We just checked your PR and seems the link still has some issues. Could you please check out the How to Contribute on our Youtube Channel? Here is the link:https://youtu.be/996ZhT-kEDM?si=UGcvdw1JyPPhBpM9
You can also join our discord to communicate with our team more efficiently. Thank you!

**Comment by wenzhuo2022** [comment]
Dear @ayan-joshi , could you please find the link of your AI Agent according to the following image shows and reply it to us? 
image
image
image

**Pull request closed without merging**
