### PR TITLE
Create Weather-App.md

### PR DESCRIPTION
**Pull request by nabinbhatt**
## 📝 Description

App that allows users to check the current weather conditions for a specific location. The app fetches weather data from the OpenWeatherMap API and displays it in a easy-to-read format.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

hacktoberfest

### CODE REVIEW

**Comment by AruSeito** [comment]
Hello, I think this data may not be very accurate. Because The 3.5 model is not real-time, we cannot merge this.

**Comment by nabinbhatt** [comment]
> Hello, I think this data may not be very accurate. Because The 3.5 model is not real-time, we cannot merge this.

Thank you for reviewing the PR. I'd like to clarify that I am not using GPT and this is not an ai-agent. The weather info is based on the data provided by openweathermap API.

**Comment by AruSeito** [comment]
@nabinbhatt
Hello,It's my bad.I replied to the wrong PR.LOL

**Comment by nabinbhatt** [comment]
No worries at all!
By the way, I noticed the label on the PR is currently set to "ILLA with AI", but I believe it should be "build with ILLA". Could you please update the label accordingly?

**Pull request merged**
