### PR TITLE
Create Personalized-Workout-Generator.md

### PR DESCRIPTION
**Pull request by adkbbx**
This is an AI agent that can generate personalised workouts based on body type and goals of the individual.

## 📝 Description
This is an AI agent related with issue #2378 this agent can generate personalised workouts based on body type and goals of the individual.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

lol

### CODE REVIEW

**Comment by wenzhuo2022** [comment]
Dear @adkbbx , thank you very much for your contribution. We found that you use these two variable ({{Bodytype}}  and {{Goal}} ) in your AI Agent, but have not created them in a variable. Please fixed it. Looking forward to your update. 

Here is an example: 
image

**Comment by adkbbx** [comment]
Dear @wenzhuo2022,
Thank you for you feedback, I have updated the agent as requested do let me know if what I have done is correct or if any other changes are required.

**Comment by adkbbx** [comment]
@wenzhuo2022,
Could you please rewiew this agent as well.

**Comment by AruSeito** [comment]
@adkbbx 
Hello, we will continue the review next Monday. 
Have a nice weekend.

**Pull request merged**
