### PR TITLE
Create NutritionCalci.md

### PR DESCRIPTION
**Pull request by git-dibwar**
## 📝 Description

Add a brief description.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

lol

### CODE REVIEW

**Comment by AruSeito** [comment]
Hello, your PR does not meet the requirements. Please paste the agent or App link you created in markdown @git-dibwar

**Comment by git-dibwar** [comment]
Does this meet the requirements now?

**Comment by AruSeito** [comment]
> Does this meet the requirements now?

Yes，Please wait for my colleague to review

**Comment by git-dibwar** [comment]
please approve

**Comment by git-dibwar** [comment]
please look into this.

**Pull request merged**
