### PR TITLE
Create Holopin Board Preview.md

### PR DESCRIPTION
**Pull request by timoransky**
## 📝 Description

Display your Holopin board with your username

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

lol

### CODE REVIEW

**Comment by AruSeito** [comment]
Hello,
The App may be has some problem.The https://www.holopin.me/ is unsafe,cause img not display

**Comment by wenzhuo2022** [comment]
Dear user, 
Thanks for your contribution. You can change the following field of input1 to https://holopin.me/{{input1.value}} so that the image can load successfully. 
image

**Comment by timoransky** [comment]
Hey @wenzhuo2022, thank you for the feedback. I fixed the URL address so everything should work as expected now.

**Comment by wenzhuo2022** [comment]
The second badge plz @holopin-bot @timoransky

**Pull request merged**
