### PR TITLE
Create DocumentGenerator.md

### PR DESCRIPTION
**Pull request by harshita1611**
## 📝 Description

Add a brief description.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

lol

### CODE REVIEW

**Comment by wenzhuo2022** [comment]
Dear @harshita1611 , please attach your AI Agent link, starting with illa.ai, to facilitate our review.

**Comment by harshita1611** [comment]
https://illa.ai/ai-agent/ILAex4p1C7WI/detail?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxNDY3OCwidXVpZCI6IjBlYjNkYmZjLTJlNjMtNDIyNS1hN2EyLTA5NDFiODg3ZTQ3NSIsInJuZCI6IjAwMDc3NCIsImlzcyI6IklMTEEiLCJleHAiOjE2OTc4MjA2Njl9.0HZiIAo5qt77gd0Y38AsbiClDqVN7Y9SrZWn6Ge9b_g

**Comment by wenzhuo2022** [comment]
Dear @harshita1611 , thank you very much for your reply.  We found that you sent a link with a token. For security reasons, we have deleted this comment. Please do not send this link with a token to others at any time. We have seen your AI Agent and will give you a new reply later.

**Comment by wenzhuo2022** [comment]
Maybe you want the AI Agent to send the documentation of HTML. If it's for this purpose, you can delete the variable. If you want to dynamically provide documentation based on your needs, you can update it as follows. 

image

**Pull request merged**
