### PR TITLE
fix(bug): Modal popup incorrect position Issue

### PR DESCRIPTION
**Pull request by ManishDait**
… action

## 📝 Description
This PR resolves issue #2090, where modal popup position is incorrect when adding event handler to action during left pannel is close as shown:
#### Issue:
prevr2

- Here the position of modal popup is incorrect.

Add a brief description.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information
The problem seems that the BaseModal width is set to `400px` as shown in below snippet:
```typescript
// Modal Component that is return
  return (
    <div css={css(modalWrapperStyle, _css)}>
      {_header}
      <Suspense>{renderBody}</Suspense>
      {extraElement}
    </div>
  )
```
```typescript
// Style of Modal
export const modalWrapperStyle = css`
  width: 400px;
`
```
which causes the BaseModal(Popup) to move from left to rigth as the the actionList pannel min width and width is `255px`. The reson is that on closing the left pannel only actionList Pannel width `255px` width remains. which causes popup to move right. 
By changing the width of the actionList and BaseModal the Popup remain in correct position.

#### Left pannel enable:
resultnew1

#### Left pannel disable:
saveresult1

lol

### CODE REVIEW

**Comment by AruSeito** [comment]
@ManishDait May be cuase other bug.Plz check EventHanlder Modal position when open on Inspect panel.

**Comment by ManishDait** [comment]
Hi @AruSeito, I've made some updates. Could you please review them and provide any feedback or suggestions if necessary?

**Comment by AruSeito** [comment]
Sorry, @ManishDait 
The current changes do not meet our design specifications, I need to communicate with our designer

**Comment by ManishDait** [comment]
Ok

**Comment by wenzhuo2022** [comment]
Dear user, 
Thank you for taking the time to submit a pull request to our open-source project. We appreciate your contribution and enthusiasm for our project.

After careful consideration and discussion within our team, we think that changing the popup position, such as having it appear at the indicated location when there is insufficient space on the left side, would be a better option.

image

Looking forward to your update.

**Pull request merged**
