### PR TITLE
feat: login not need email when use root

### PR DESCRIPTION
**Pull request by AruSeito**
## 📝 Description

Add a brief description.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

lol

### CODE REVIEW

**Comment by PeixyJ** [comment]
This update does not take effect in Docker.

docker pull illasoft/illa-frontend:latest

**Comment by AruSeito** [comment]
Hello @PeixyJ ,please provide a little bit more details on this error you got. What API request did ILLA Builder run? And what this request outputs did you receive? Thanks

**Comment by PeixyJ** [comment]
Hello @AruSeito,thank you for your reply,i see. thank you.but i not find kubernetes script.do you know?

**Comment by AruSeito** [comment]
@PeixyJ ，It's there [kubernetes](https://github.com/illacloud/deploy-illa-manually/tree/main/kubernetes)

**Comment by PeixyJ** [comment]
@AruSeito there kubernetes is cloud version,i not find SELF-HOST version of kubernetes.

**Comment by karminski** [comment]
@PeixyJ hi, the Kubernetes deployment method only supports cloud version for now.

**Comment by PeixyJ** [comment]
@karminski hi,now i kown. thank your reply.

**Pull request merged**
