### PR TITLE
Create My Therapist

### PR DESCRIPTION
**Pull request by nandinisahu407**
Create a chatbot that can offer mental health support and counseling to individuals. It should be able to understand and empathize with users and help them cope

## 📝 Description

Add a brief description.

## 💣 Is this a breaking change (Yes/No):

- [x] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

lol

### CODE REVIEW

**Comment by AruSeito** [comment]
@nandinisahu407 Hello, your promoto seems to have some problems. If you need to use variables, please use `{{}}` instead of `{}`

**Comment by nandinisahu407** [comment]
@AruSeito updated suggested changes,kindly merge it

**Comment by nandinisahu407** [comment]
> @nandinisahu407 Hello, your Prompt seems to have some problems. If you need to use variables, please use `{{}}` instead of `{}`

@AruSeito updated suggested changes, let me know if any more changes need to be done

**Comment by nandinisahu407** [comment]
@wenzhuo2022 kindly merge this

**Pull request merged**
