### PR TITLE
Create LeetCodeStatsCardGenerator.md

### PR DESCRIPTION
**Pull request by bkpecho**
## 📝 Description

Instantly display your LeetCode account stats in a sleek, customizable card with the LeetCode Stats Card Generator.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

Fast try: https://illa.ai/app/ILAfx4p1C7Jx/detail

### CODE REVIEW

**Comment by bkpecho** [comment]
Hello @AruSeito @wenzhuo2022 Thank you for the badges! I submitted 2 ILLA App, but only got this "ILLA App" badge. 

Should I submit a third application to get the 2nd ILLA app badge? Thanks! 😊

image

**Comment by wenzhuo2022** [comment]
Thank you for your help! @holopin-bot @bkpecho

**Comment by bkpecho** [comment]
Thank you! 😄🚀

image

**Comment by wenzhuo2022** [comment]
And there are other 2 badges for ILLA AI Agent contributors. We have started to distribute too. If you haven't submitted a PR for the AI Agent yet, you can give it a try ❤️

**Comment by bkpecho** [comment]
Yes, I claimed it both already. Thank you so much ILLA Team 😊🎉

**Pull request merged**
