### PR TITLE
added 'Ligament' - a Recovery and Injury Prevention bot

### PR DESCRIPTION
**Pull request by ATREAY**
## 📝 Description

This tool generates personalized fitness strategies. Users specify their fitness context and keywords to receive tailored advice on injury prevention, recovery, and safe workouts.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

closes: #2383

### CODE REVIEW

**Comment by AruSeito** [comment]
@ATREAY plz update your beta branch again and cherry pick your commit.

**Comment by AruSeito** [comment]
@ATREAY Hello,your commit is not true.It should only have this
[[added Ligament - a fitness bot](https://github.com/illacloud/illa-builder/pull/2623/commits/cd0ced12870547289cc0981a80b25b90d062be25)] commit

**Comment by AruSeito** [comment]
@ATREAY 
Hello,It still doesn’t right. You can try to upload files under our repo. Or synchronize your repo with ours and PR again.
I checked your Repo and found that the beta branch has been contaminated. If you have not change code , you can try deleting the repository and forking again.And then commit this file and PR again

**Comment by ATREAY** [comment]
Sure thing, @AruSeito! I'll close this PR and start fresh with a new one.

**Pull request closed without merging**
