### PR TITLE
Create Study plan generator.md

### PR DESCRIPTION
**Pull request by Arnavthakare19**
## 📝 Description

You enter the syllabus, days left before exam and enter subject name. It provides day to day schedule giving a organized timetable

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

Hacktoberfest2023

### CODE REVIEW

**Comment by Arnavthakare19** [comment]
@AruSeito how do i resolve the conflicts? or should i just let it be?

**Comment by AruSeito** [comment]
@Arnavthakare19 Plz update your beta branch and commit this file again.and then close this pr and submit new pr

**Comment by Arnavthakare19** [comment]
ok

**Comment by AruSeito** [comment]
@Arnavthakare19 Hello,I find some your PR need same operation.
#2636 #2644 #2643

**Comment by Arnavthakare19** [comment]
I am looking into it @AruSeito 
Will update them in under 10 mins and close these PRs

**Pull request closed without merging**
