### PR TITLE
feat: Line-Coding-Waves

### PR DESCRIPTION
**Pull request by malivinayak**
# Line-Coding-Waves
Line encoding is the process of converting digital data into analog signals suitable for transmission over communication channels. Fast try: https://illa.ai/ai-agent/ILAex4p1C73k/detail

## 📝 Description

Line encoding is the process of converting digital data into analog signals suitable for transmission over communication channels.

We will be generating waveforms for Unipolar NRZ, Polar NRZ-L, Polar NRZ-I, Polar RZ, Manchester, Differential Manchester, AMI, and Pseudoternary line encoding techniques.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

Github Repo - https://github.com/malivinayak/Line-Coding-Waves
Live Deployment - https://malivinayak.github.io/Line-Coding-Waves/

### CODE REVIEW

**Comment by wenzhuo2022** [comment]
Dear user, 
Thanks for your contribution. We found that the Agent you created did not meet the requirements when we reviewed it, so the PR was not accepted. If you need cooperation, please contact business@illasoft.com. We welcome cooperation with any open-source project to build an open and friendly open-source environment.

**Comment by wenzhuo2022** [comment]
We aim for the AI Agent itself to be functional and provide effective assistance to users in solving problems. You can also explore enabling the AI Agent to convert input content into linear encoded waveforms, for example, as demonstrated in the provided image(It's just an example. Please forgive me for any inaccuracies in my example regarding the waveform graph, as I am not knowledgeable in that area. You can leverage your expertise and guide the model on how to output the content by providing instructions in the prompt.). This way, when other users run your AI Agent, they can obtain useful output. Additionally, we recommend avoiding directly adding your repo address in the prompt (as we generally discourage attracting users to your repo in this manner). However, if you must include it, we suggest informing the large language model in a similar manner, indicating that the output should include this content in the form of a markdown hyperlink at the end of each response: Learn more about this topic through [GitHub Repo](your link).
image

**Comment by malivinayak** [comment]
I will start working accordingly. Thank you for your feedback.

**Comment by wenzhuo2022** [comment]
Thank you very much. Waiting for your update ❤️

**Comment by malivinayak** [comment]
Now Agent can generate waves by itself.
Waves are in form symbol `_` and `-`.
also I have removed the repo link as suggested.
Previously I was unaware of the purpose of Prompt but now I understand it properly. 

image

**Comment by malivinayak** [comment]
The result generated and the explanation of agent is up to the point.


image

**Comment by wenzhuo2022** [comment]
That's great! Thank you for your time and effort. I will add the "HACKTOBERFEST-ACCEPTED" label to it. Our colleagues will merge it once they are back at work.

**Comment by malivinayak** [comment]
Thank You @wenzhuo2022 for give me second chance. 
Thank You @AruSeito

**Comment by malivinayak** [comment]
@wenzhuo2022 @AruSeito
Sorry to bother you 
image
As you can see PR's are accepted but I didn't receive holopin batches form illa
If possible can you please tell me why

**Comment by malivinayak** [comment]
@wenzhuo2022 @AruSeito 
I received the mail from illa teams.
As instructed i replied to that mail but I am receiving error as `The recipient server did not accept our requests to connect.`

image

What should I suppose to do

**Pull request merged**
