### PR TITLE
Create chess player generator.md

### PR DESCRIPTION
**Pull request by kaushal1717**
## 📝 Description

Add a brief description.

## 💣 Is this a breaking change (Yes/No):

- [x] Yes
- [] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

lol

### CODE REVIEW

**Comment by kaushal1717** [comment]
ok doing that change

**Comment by kaushal1717** [comment]
image
Will it work?

**Comment by wenzhuo2022** [comment]
> image
> Will it work?

Yes, it works. Thanks for your time ❤️.

**Comment by kaushal1717** [comment]
Now my PR will merge?

**Pull request merged**
