### PR TITLE
add: Github Stats.md

### PR DESCRIPTION
**Pull request by AvaterClasher**
## 📝 Description

A website that show's User's their github stats when they enter their Username.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

lol

### CODE REVIEW

**Comment by AvaterClasher** [comment]
@AruSeito This is build with illa project and not an illa-ai project

**Comment by AruSeito** [comment]
Hello,
We suggest that you split the two files into two PRs instead of treating them as one PR

**Comment by AvaterClasher** [comment]
Did it @AruSeito

**Comment by AvaterClasher** [comment]
@wenzhuo2022  Got only one badge for the illa app builder

**Comment by wenzhuo2022** [comment]
Here it is! @holopin-bot @AvaterClasher

**Comment by wenzhuo2022** [comment]
The other two badges for the AI Agent have been sent to the PR of the AI Agent. If you haven't received them, please feel free to contact us.

**Pull request merged**
